CREATE OR REPLACE TRIGGER amount_updater_trigger
    AFTER INSERT OR DELETE ON departments
    FOR EACH ROW
BEGIN
CASE
    WHEN INSERTING THEN
        UPDATE LOCATIONS SET DEPARTMENT_AMOUNT = DEPARTMENT_AMOUNT + 1 WHERE LOCATION_ID = :NEW.LOCATION_ID;
    WHEN DELETING THEN
        UPDATE LOCATIONS SET DEPARTMENT_AMOUNT = DEPARTMENT_AMOUNT - 1 WHERE LOCATION_ID = :OLD.LOCATION_ID;
    END CASE;
END;